name: push tests
on: push
env:
  CI: true
jobs:
  my-job:
    strategy:
      # Node versions list
      matrix:
        node-version: [20.x]
    runs-on: ubuntu-latest
    steps:
      - run: npm ci
      - run: make test
